### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [javamanatee/arthur-machen_the-secret-glory#1]
# dedication.xhtml

- [x] Replace:
```
			<p>To</p>
			<p>Vincent Starrett</p>
```
with:
```
			<p>To<br/>
			Vincent Starrett</p>
```

# chapter-1.xhtml

- [x] Title case `<i epub:type="se:name.publication.book">Daedalus; or, The Secret of the Labyrinth</i>`.

- [x] Surround "Chorus." and the stanza starting with "Lupton, follow away!" with a `<div>` element. Format "Chorus." as a header ([SEMOS 7.2.10.8](https://standardebooks.org/manual/1.7.3/single-page#7.2.10.8)).

# chapter-2.xhtml

- [x] Surround "Chorus." and the stanza starting with "Look out for ‘brooks,’ or you’re sure to drown," with a `<div>` element. Format "Chorus." as a header.

# endnotes.xhtml

- [x] In note 3, convert the unsemanticated `<i>` element to an `<em>` element.

# local.css

- [x] Add dedication CSS ([SEMOS 7.3.1](https://standardebooks.org/manual/1.7.3/single-page#7.3.1)).

**Comment by javamanatee** [comment]
I made the fixes.  I have italics for the chorus header to match the scan, not exactly like the SEMOS example.  Let me know if that's wrong.  I also had to make the CSS selector for header more specific to get the center alignment, otherwise it seems to get overridden by the other rules.

**Comment by EmmaSweeney** [comment]
- [x] One more thing, you need to copy and paste all of the dedication CSS from the manual:

```
/* Centered dedications */
section[epub|type~="dedication"]{
	text-align: center;
}

section[epub|type~="dedication"] > *{
	display: inline-block;
	margin: auto;
	margin-top: 3em;
	max-width: 80%;
}

@supports(display: flex){
	section[epub|type~="dedication"]{
		align-items: center;
		box-sizing: border-box;
		display: flex;
		flex-direction: column;
		justify-content: center;
		min-height: calc(98vh - 3em);
		padding-top: 3em;
	}

	section[epub|type~="dedication"] > *{
		margin: 0;
	}
}
/* End centered dedications */
```

**Comment by javamanatee** [comment]
Wow, I don't know how I missed that!  Should be ready now.
